name = "ClaudeCodeSDK"
uuid = "38ea0fac-78ee-46bd-bc10-f52e7269b833"
version = "0.1.0"
authors = ["Claude Code and Satoshi Terasaki"]
description = "Julia SDK for Claude Code"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1.10"
JSON = "0.21"
HTTP = "1.7"
